### ISSUE TITLE
does not work with Catalina ...

### ISSUE THREAD

**Issue by alucardxs** [randyzhong/OS-X-HP-EliteDesk-800-G3-DM-Clover#2]
Thanks for your files but can't install Catalina on mine.
I'm stuck at apfs 1683 or apfs 1689 during installation ...
Any ideas ?

Thanks

**Comment by randyzhong** [comment]
Can you try to add EC0 rename patch?
Comment: change EC0 to EC
Find: 4543305F
Replace: 45435F5F

**Comment by alucardxs** [comment]
Seems ok now, thanks you dude for your help !
